In [18]:
#  Import dependencies and read the csv.
#!pip install pandas
import pandas as pd 
monsters_df = pd.read_csv("dnd_monsters.csv")
monsters_df.head()

,name,url,cr,type,size,ac,hp,speed,align,legendary,source,str,dex,con,int,wis,cha
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,1/4,humanoid (aarakocra),Medium,12,13,fly,neutral good,NaN,Monster Manual (BR),10.0,14.0,10.0,11.0,12.0,11.0
1,abjurer,NaN,9,humanoid (any race),Medium,12,84,NaN,any alignment,NaN,Volo's Guide to Monsters,NaN,NaN,NaN,NaN,NaN,NaN
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10,aberration,Large,17,135,swim,lawful evil,Legendary,Monster Manual (SRD),21.0,9.0,15.0,18.0,15.0,18.0
3,abominable-yeti,NaN,9,monstrosity,Huge,15,137,NaN,chaotic evil,NaN,Monster Manual,NaN,NaN,NaN,NaN,NaN,NaN
4,acererak,NaN,23,undead,Medium,21,285,NaN,neutral evil,NaN,Adventures (Tomb of Annihilation),NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#Drop columns we don't need (align & source)
monsters_df = monsters_df.drop(columns=['align', 'source'])
monsters_df.head()

,name,url,cr,type,size,ac,hp,speed,legendary,str,dex,con,int,wis,cha
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,1/4,humanoid (aarakocra),Medium,12,13,fly,NaN,10.0,14.0,10.0,11.0,12.0,11.0
1,abjurer,NaN,9,humanoid (any race),Medium,12,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10,aberration,Large,17,135,swim,Legendary,21.0,9.0,15.0,18.0,15.0,18.0
3,abominable-yeti,NaN,9,monstrosity,Huge,15,137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,acererak,NaN,23,undead,Medium,21,285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
#Drop Nan rows ONLY from str
monsters_df = monsters_df.dropna(subset=['str'])
monsters_df.head()

,name,url,cr,type,size,ac,hp,speed,legendary,str,dex,con,int,wis,cha
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,1/4,humanoid (aarakocra),Medium,12,13,fly,NaN,10.0,14.0,10.0,11.0,12.0,11.0
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10,aberration,Large,17,135,swim,Legendary,21.0,9.0,15.0,18.0,15.0,18.0
5,acolyte,https://www.aidedd.org/dnd/monstres.php?vo=aco...,1/4,humanoid (any race),Medium,10,9,NaN,NaN,10.0,10.0,10.0,10.0,14.0,11.0
6,adult-black-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14,dragon,Huge,19,195,"fly, swim",Legendary,23.0,14.0,21.0,14.0,13.0,17.0
8,adult-blue-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,16,dragon,Huge,19,225,fly,Legendary,25.0,10.0,23.0,16.0,15.0,19.0

In [21]:
#Check data types and changed any if needed
monsters_df.dtypes

name          object
url           object
cr            object
type          object
size          object
ac             int64
hp             int64
speed         object
legendary     object
str          float64
dex          float64
con          float64
int          float64
wis          float64
cha          float64
dtype: object

In [22]:
#CR column should be float but we need to conver fractions
#take from: https://stackoverflow.com/questions/69112191/convert-fractional-values-to-decimal-in-pandas
def convert(frac):
    if '/' in frac:
        num, den = frac.split('/')
        return (int(num)/int(den))
    else:
        return float(frac)

monsters_df['cr'] = monsters_df['cr'].apply(convert)
monsters_df.head()

,name,url,cr,type,size,ac,hp,speed,legendary,str,dex,con,int,wis,cha
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,0.25,humanoid (aarakocra),Medium,12,13,fly,NaN,10.0,14.0,10.0,11.0,12.0,11.0
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10.00,aberration,Large,17,135,swim,Legendary,21.0,9.0,15.0,18.0,15.0,18.0
5,acolyte,https://www.aidedd.org/dnd/monstres.php?vo=aco...,0.25,humanoid (any race),Medium,10,9,NaN,NaN,10.0,10.0,10.0,10.0,14.0,11.0
6,adult-black-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14.00,dragon,Huge,19,195,"fly, swim",Legendary,23.0,14.0,21.0,14.0,13.0,17.0
8,adult-blue-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,16.00,dragon,Huge,19,225,fly,Legendary,25.0,10.0,23.0,16.0,15.0,19.0

In [23]:
#Check dtypes and convert if needed
monsters_df.dtypes

name          object
url           object
cr           float64
type          object
size          object
ac             int64
hp             int64
speed         object
legendary     object
str          float64
dex          float64
con          float64
int          float64
wis          float64
cha          float64
dtype: object

In [24]:
#Split speed column on ','
monsters_df[['fly', 'swim']] = monsters_df['speed'].str.split(',', expand=True)
monsters_df = monsters_df.drop(columns='speed')

monsters_df.head(10)

,name,url,cr,type,size,ac,hp,legendary,str,dex,con,int,wis,cha,fly,swim
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,0.25,humanoid (aarakocra),Medium,12,13,NaN,10.0,14.0,10.0,11.0,12.0,11.0,fly,None
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10.00,aberration,Large,17,135,Legendary,21.0,9.0,15.0,18.0,15.0,18.0,swim,None
5,acolyte,https://www.aidedd.org/dnd/monstres.php?vo=aco...,0.25,humanoid (any race),Medium,10,9,NaN,10.0,10.0,10.0,10.0,14.0,11.0,NaN,NaN
6,adult-black-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14.00,dragon,Huge,19,195,Legendary,23.0,14.0,21.0,14.0,13.0,17.0,fly,swim
8,adult-blue-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,16.00,dragon,Huge,19,225,Legendary,25.0,10.0,23.0,16.0,15.0,19.0,fly,None
9,adult-brass-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,13.00,dragon,Huge,18,172,Legendary,23.0,10.0,21.0,14.0,13.0,17.0,fly,None
10,adult-bronze-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,15.00,dragon,Huge,19,212,Legendary,25.0,10.0,23.0,16.0,15.0,19.0,fly,swim
11,adult-copper-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14.00,dragon,Huge,18,184,Legendary,23.0,12.0,21.0,18.0,15.0,17.0,fly,None
12,adult-gold-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,17.00,dragon,Huge,19,256,Legendary,27.0,14.0,25.0,16.0,15.0,24.0,fly,swim
13,adult-green-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,15.00,dragon,Huge,19,207,Legendary,23.0,12.0,21.0,18.0,15.0,17.0,fly,swim

In [25]:
#Replace NaN values
monsters_df[['fly', 'swim']] = monsters_df[['fly', 'swim']].fillna(0)
monsters_df.head()

,name,url,cr,type,size,ac,hp,legendary,str,dex,con,int,wis,cha,fly,swim
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,0.25,humanoid (aarakocra),Medium,12,13,NaN,10.0,14.0,10.0,11.0,12.0,11.0,fly,0
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10.00,aberration,Large,17,135,Legendary,21.0,9.0,15.0,18.0,15.0,18.0,swim,0
5,acolyte,https://www.aidedd.org/dnd/monstres.php?vo=aco...,0.25,humanoid (any race),Medium,10,9,NaN,10.0,10.0,10.0,10.0,14.0,11.0,0,0
6,adult-black-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14.00,dragon,Huge,19,195,Legendary,23.0,14.0,21.0,14.0,13.0,17.0,fly,swim
8,adult-blue-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,16.00,dragon,Huge,19,225,Legendary,25.0,10.0,23.0,16.0,15.0,19.0,fly,0

In [26]:
#Drop extra strings in fly+swim columns
monsters_df['fly'] = monsters_df['fly'].replace(['fly'], 'Yes')
monsters_df['fly'] = monsters_df['fly'].replace(['swim', 0], 'No')
monsters_df['swim'] = monsters_df['swim'].replace([' swim'], 'Yes')
monsters_df['swim'] = monsters_df['swim'].replace(['fly', 0], 'No')
monsters_df.head()

,name,url,cr,type,size,ac,hp,legendary,str,dex,con,int,wis,cha,fly,swim
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,0.25,humanoid (aarakocra),Medium,12,13,NaN,10.0,14.0,10.0,11.0,12.0,11.0,Yes,No
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10.00,aberration,Large,17,135,Legendary,21.0,9.0,15.0,18.0,15.0,18.0,No,No
5,acolyte,https://www.aidedd.org/dnd/monstres.php?vo=aco...,0.25,humanoid (any race),Medium,10,9,NaN,10.0,10.0,10.0,10.0,14.0,11.0,No,No
6,adult-black-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14.00,dragon,Huge,19,195,Legendary,23.0,14.0,21.0,14.0,13.0,17.0,Yes,Yes
8,adult-blue-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,16.00,dragon,Huge,19,225,Legendary,25.0,10.0,23.0,16.0,15.0,19.0,Yes,No

In [27]:
#Eliminate any () in type column to clean
import re
formula = r'\([^()]*\)'
def remove_parentheses(type):
    return re.sub(formula, '', type)
monsters_df['cleaned type'] = monsters_df['type'].apply(remove_parentheses)
monsters_df.sample(10)

,name,url,cr,type,size,ac,hp,legendary,str,dex,con,int,wis,cha,fly,swim,cleaned type
726,xorn,https://www.aidedd.org/dnd/monstres.php?vo=xorn,5.00,elemental,Medium,19,73,NaN,17.0,10.0,22.0,11.0,10.0,11.0,No,No,elemental
561,satyr,https://www.aidedd.org/dnd/monstres.php?vo=satyr,0.50,fey,Medium,14,31,NaN,12.0,16.0,11.0,12.0,10.0,14.0,No,No,fey
549,riding-horse,https://www.aidedd.org/dnd/monstres.php?vo=rid...,0.25,beast,Large,10,13,NaN,16.0,10.0,12.0,2.0,11.0,7.0,No,No,beast
557,sahuagin,https://www.aidedd.org/dnd/monstres.php?vo=sah...,0.50,humanoid (sahuagin),Medium,12,22,NaN,13.0,11.0,12.0,12.0,13.0,9.0,No,No,humanoid
548,rhinoceros,https://www.aidedd.org/dnd/monstres.php?vo=rhi...,2.00,beast,Large,11,45,NaN,21.0,8.0,15.0,2.0,12.0,6.0,No,No,beast
359,hippogriff,https://www.aidedd.org/dnd/monstres.php?vo=hip...,1.00,monstrosity,Large,11,19,NaN,17.0,13.0,13.0,2.0,12.0,8.0,Yes,No,monstrosity
202,duergar,https://www.aidedd.org/dnd/monstres.php?vo=due...,1.00,humanoid (dwarf),Medium,16,26,NaN,14.0,11.0,14.0,11.0,10.0,9.0,No,No,humanoid
668,tyrannosaurus-rex,https://www.aidedd.org/dnd/monstres.php?vo=tyr...,8.00,beast,Huge,13,136,NaN,25.0,10.0,19.0,2.0,12.0,9.0,No,No,beast
213,eagle,https://www.aidedd.org/dnd/monstres.php?vo=eagle,0.00,beast,Small,12,3,NaN,6.0,15.0,10.0,2.0,14.0,7.0,Yes,No,beast
512,phase-spider,https://www.aidedd.org/dnd/monstres.php?vo=pha...,3.00,monstrosity,Large,13,32,NaN,15.0,15.0,12.0,6.0,10.0,6.0,No,No,monstrosity

In [28]:
#Drop type column and rename cleaned_type
monsters_df = monsters_df.drop(columns=['type'])
monsters_df.rename(columns= {'cleaned type': 'type'}, inplace=True)
monsters_df.head()

,name,url,cr,size,ac,hp,legendary,str,dex,con,int,wis,cha,fly,swim,type
0,aarakocra,https://www.aidedd.org/dnd/monstres.php?vo=aar...,0.25,Medium,12,13,NaN,10.0,14.0,10.0,11.0,12.0,11.0,Yes,No,humanoid
2,aboleth,https://www.aidedd.org/dnd/monstres.php?vo=abo...,10.00,Large,17,135,Legendary,21.0,9.0,15.0,18.0,15.0,18.0,No,No,aberration
5,acolyte,https://www.aidedd.org/dnd/monstres.php?vo=aco...,0.25,Medium,10,9,NaN,10.0,10.0,10.0,10.0,14.0,11.0,No,No,humanoid
6,adult-black-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,14.00,Huge,19,195,Legendary,23.0,14.0,21.0,14.0,13.0,17.0,Yes,Yes,dragon
8,adult-blue-dragon,https://www.aidedd.org/dnd/monstres.php?vo=adu...,16.00,Huge,19,225,Legendary,25.0,10.0,23.0,16.0,15.0,19.0,Yes,No,dragon

In [29]:
#Remove and spaces from new column
#Modified from: https://stackoverflow.com/questions/49180379/python-remove-and-spaces-from-a-column
monsters_df.type = monsters_df.type.map(lambda x: x.replace(' ', ''))

In [30]:
#Unique values for html dropdown menu
a = monsters_df['type'].unique()
b = monsters_df['size'].unique()
print(sorted(a))
print(sorted(b))

['aberration', 'beast', 'celestial', 'construct', 'dragon', 'elemental', 'fey', 'fiend', 'giant', 'humanoid', 'monstrosity', 'ooze', 'plant', 'swarmofTinybeasts', 'undead']
['Gargantuan', 'Huge', 'Large', 'Medium', 'Small', 'Tiny']

In [31]:
#Stats for columns
stats = monsters_df[['ac', 'hp', 'str', 'dex', 'con', 'int', 'wis', 'cha']].describe()
print(stats)

               ac          hp         str         dex         con         int  \
count  401.000000  401.000000  401.000000  401.000000  401.000000  401.000000
mean    14.109726   81.463840   15.231920   12.745636   15.147132    8.324190
std      3.165111   98.069768    6.492964    3.183573    4.383012    5.694264
min      5.000000    1.000000    1.000000    1.000000    8.000000    1.000000
25%     12.000000   19.000000   11.000000   10.000000   12.000000    3.000000
50%     13.000000   45.000000   16.000000   13.000000   14.000000    8.000000
75%     17.000000  112.000000   19.000000   15.000000   17.000000   12.000000
max     25.000000  676.000000   30.000000   28.000000   30.000000   26.000000

              wis         cha
count  401.000000  401.000000
mean    11.820449   10.097257
std      3.093167    5.696755
min      2.000000    1.000000
25%     10.000000    6.000000
50%     12.000000    9.000000
75%     13.000000   14.000000
max     27.000000   30.000000

In [32]:
stats_df = monsters_df[['ac', 'hp', 'str', 'dex', 'con', 'int', 'wis', 'cha']]
stats_df

     ac   hp   str   dex   con   int   wis   cha
0    12   13  10.0  14.0  10.0  11.0  12.0  11.0
2    17  135  21.0   9.0  15.0  18.0  15.0  18.0
5    10    9  10.0  10.0  10.0  10.0  14.0  11.0
6    19  195  23.0  14.0  21.0  14.0  13.0  17.0
8    19  225  25.0  10.0  23.0  16.0  15.0  19.0
..   ..  ...   ...   ...   ...   ...   ...   ...
753  12   66  16.0  14.0  13.0  14.0  12.0  16.0
755  14   71  16.0  14.0  13.0  14.0  12.0  16.0
757  11   40  11.0  12.0  11.0  13.0  12.0  14.0
759  21  580  27.0  24.0  28.0  26.0  27.0  30.0
760   8   22  13.0   6.0  16.0   3.0   6.0   5.0

[401 rows x 8 columns]

In [34]:
#Export final DataFrame
monsters_df.to_csv("cleaned_dnd_monsters.csv", encoding='utf-8', index=False)
stats_df.to_csv("cleaned_stats.csv", encoding='utf-8', index=False)